project:
  type: website

website:
  title: "Class Visit Slides"
  page-navigation: false
  navbar:
    left:
      - text: "All decks"
        href: index.html

format:
  revealjs:
    theme: default
    slide-number: true
    embed-resources: true
